//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestVPKIcon.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestVPKIcon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string LANGUAGE_ABOUT_CN {
            get {
                return ResourceManager.GetString("LANGUAGE_ABOUT_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string LANGUAGE_ABOUT_EN {
            get {
                return ResourceManager.GetString("LANGUAGE_ABOUT_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 關於 的本地化字符串。
        /// </summary>
        public static string LANGUAGE_ABOUT_TW {
            get {
                return ResourceManager.GetString("LANGUAGE_ABOUT_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于本应用 的本地化字符串。
        /// </summary>
        public static string LANGUAGE_ABOUTME_CN {
            get {
                return ResourceManager.GetString("LANGUAGE_ABOUTME_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About This App 的本地化字符串。
        /// </summary>
        public static string LANGUAGE_ABOUTME_EN {
            get {
                return ResourceManager.GetString("LANGUAGE_ABOUTME_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 關於本軟體 的本地化字符串。
        /// </summary>
        public static string LANGUAGE_ABOUTME_TW {
            get {
                return ResourceManager.GetString("LANGUAGE_ABOUTME_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是一个PSV VPK的windows图标小扩展。
        ///安装后可以在资源管理器中显示VPK的图标。
        ///请确认您的电脑安装了.NET framework 4.5或以上版本。 的本地化字符串。
        /// </summary>
        public static string LANGUAGE_DESCRIPTION_CN {
            get {
                return ResourceManager.GetString("LANGUAGE_DESCRIPTION_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is a simple shell extension for psvita vpk applications.
        ///It can show vpk icons in Windows Explorer.
        ///Make sure you have the .NET framework 4.5+ installed. 的本地化字符串。
        /// </summary>
        public static string LANGUAGE_DESCRIPTION_EN {
            get {
                return ResourceManager.GetString("LANGUAGE_DESCRIPTION_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 這是一個PSV VPK的windows圖標小擴展。
        ///安裝后可以在Windows 檔案總管中顯示VPK圖標。
        ///請確認您的電腦安裝了.NET framework 4.5或以上版本。 的本地化字符串。
        /// </summary>
        public static string LANGUAGE_DESCRIPTION_TW {
            get {
                return ResourceManager.GetString("LANGUAGE_DESCRIPTION_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装 的本地化字符串。
        /// </summary>
        public static string LANGUAGE_INSTALL_CN {
            get {
                return ResourceManager.GetString("LANGUAGE_INSTALL_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install 的本地化字符串。
        /// </summary>
        public static string LANGUAGE_INSTALL_EN {
            get {
                return ResourceManager.GetString("LANGUAGE_INSTALL_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安裝 的本地化字符串。
        /// </summary>
        public static string LANGUAGE_INSTALL_TW {
            get {
                return ResourceManager.GetString("LANGUAGE_INSTALL_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除 的本地化字符串。
        /// </summary>
        public static string LANGUAGE_UNINSTALL_CN {
            get {
                return ResourceManager.GetString("LANGUAGE_UNINSTALL_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstall 的本地化字符串。
        /// </summary>
        public static string LANGUAGE_UNINSTALL_EN {
            get {
                return ResourceManager.GetString("LANGUAGE_UNINSTALL_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除 的本地化字符串。
        /// </summary>
        public static string LANGUAGE_UNINSTALL_TW {
            get {
                return ResourceManager.GetString("LANGUAGE_UNINSTALL_TW", resourceCulture);
            }
        }
    }
}
